name: ClandestinoCustom
version: ${project.version}
author: FoxSGR
main: net.foxsgr.clandestinocustom.plugin.ClandestinoCustom
api-version: 1.15

softdepend:
  - Essentials

commands:
  ajuda:
    description: Get help.
    usage: "Usage: /ajuda [help name]"
    permission-message: You not have have permission to use this command.
    aliases:
      - helps
  diskspace:
    description: Disk space analysis command.
    usage: "Usage: /diskspace [sort [amount]] (path)"
    permission-message: You not have have permission to use this command.
  sellable:
    description: Essentials worth list.
    usage: "Usage: /sellable"
    permission-message: You not have have permission to use this command.
    aliases:
      - vendiveis
      - vendaveis
      - valores
      - valor
  cc:
    description: Internal things command.
    usage: "Usage: /cc"
  vantagens:
    description: Show rank advantagens.
    usage: "Usage: /vantagens [rank]"
    aliases:
      - perks
      - advantages

permissions:
  clandestinocustom.*:
    description: Allows every ClandestinoCustom command.
    default: op
    children:
      clandestinocustom.sellable:
        description: Allows listing every sellable item and its price.
        default: true
      clandestinocustom.diskspace:
        description: Allows using the ClandestinoCustom diskspace command.
        default: op
      clandestinocustom.ajuda.*:
        description: Allows every ClandestinoCustom Ajuda command.
        default: op
        children:
          clandestinocustom.ajuda.reload:
            description: Allows reloading ClandestinoCustom's ajudas command.
            default: op
      clandestinocustom.cc.*:
        description: Allows every internal things command.
        default: op
        children:
          clandestinocustom.cc.autorecocheck:
            description: If the player has this permission, he is allowed to automatically reconnect using our mod.
            default: op
